package br.edu.utfpr.gestaofaturasicoob.models

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Represents an automated financial insight
 * Generated by the system to help users understand their spending patterns
 */
@Parcelize
data class Insight(
    val id: String = "",
    val title: String,
    val description: String,
    val type: InsightType,
    val severity: InsightSeverity = InsightSeverity.INFO,
    val iconRes: Int? = null,
    val actionable: Boolean = false,
    val actionText: String? = null,
    val relatedCategoryId: String? = null,
    val createdAt: Long = System.currentTimeMillis()
) : Parcelable {
    fun toMap(): Map<String, Any?> {
        return mapOf(
            "id" to id,
            "title" to title,
            "description" to description,
            "type" to type.name,
            "severity" to severity.name,
            "iconRes" to iconRes,
            "actionable" to actionable,
            "actionText" to actionText,
            "relatedCategoryId" to relatedCategoryId,
            "createdAt" to createdAt
        )
    }

    companion object {
        fun fromMap(map: Map<String, Any?>): Insight {
            return Insight(
                id = map["id"] as? String ?: "",
                title = map["title"] as? String ?: "",
                description = map["description"] as? String ?: "",
                type = InsightType.valueOf(map["type"] as? String ?: "GENERAL"),
                severity = InsightSeverity.valueOf(map["severity"] as? String ?: "INFO"),
                iconRes = (map["iconRes"] as? Number)?.toInt(),
                actionable = map["actionable"] as? Boolean ?: false,
                actionText = map["actionText"] as? String,
                relatedCategoryId = map["relatedCategoryId"] as? String,
                createdAt = (map["createdAt"] as? Number)?.toLong() ?: System.currentTimeMillis()
            )
        }
    }
}

/**
 * Types of insights that can be generated
 */
enum class InsightType {
    GOAL_WARNING,           // Goal at 80% or exceeded
    SPENDING_INCREASE,      // Spending increased significantly
    SPENDING_DECREASE,      // Spending decreased significantly
    INSTALLMENT_WARNING,    // Installment on recurring category
    HIGH_EXPENSE,          // Single expense above threshold
    GENERAL                // Generic insight
}

/**
 * Severity levels for insights
 */
enum class InsightSeverity {
    INFO,      // Informational, neutral
    WARNING,   // Requires attention
    CRITICAL   // Urgent action needed
}

